name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  runApiTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Test Connectivity to APIs
        run: |
          echo "Pinging MockAPI..."
          ping -c 4 6885cfeff52d34140f6a9e3b.mockapi.io || true

          echo "Pinging QACart..."
          ping -c 4 todo.qacart.com || true

      - name: Run Maven Tests
        run: mvn clean test -e -X

      - name: Upload Surefire Reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports
